[package]
name = "nyaasi"
version = "0.1.0"
authors = ["natanbc <natanbc@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap =             "2.33.0"
kuchiki =          "0.7.3"
reqwest =          "0.9.20"
serde_urlencoded = "0.5.3"
